### ISSUE TITLE
Fancy adding these:

### ISSUE THREAD

**Issue by CromonMS** [coliff/caniuse.email#18]
www.protonmail.com
some insight: https://protonmail.com/support/knowledge-base/formatting-messages-using-different-fonts-color-fonts-ect/
I host my main email here now, so if you have any tips I can grab some info.

Thunderbird

Hows about transactional email too? for instance Sendgrid, YMLP, Mailchimp
not sure if this is outside your remit :)

ps. Cheers for the pull request dude.

**Comment by coliff** [comment]
Hey man! thanks for the suggestions. Theres an issue to add Thunderbird... its not hugely popular but I do intend to add it at some point.

With regards to Sendgrid, YMLP, Mailchimp - they are email sending platforms rather than email clients.. so they send HTML exactly as it is - its the email clients which can change the formatting and have varying degrees of HTML and CSS support - so thats what this project is for.

These are the top 10 clients in use: http://emailclientmarketshare.com/
